[package]
name = "paperless-search"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
futures.workspace = true
lance-index = "10.0.0"
lancedb.workspace = true
serde.workspace = true

[dev-dependencies]
paperless-embeddings = { path = "../embeddings" }
tempfile.workspace = true
tokio.workspace = true
