/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDocuments"];
        put?: never;
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch: operations["patchDocument"];
        trace?: never;
    };
    "/api/documents/{id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocumentFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocumentPages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/thumbnails/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getThumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/pages/{page}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPageImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["retryDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/infer-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inferDocumentMetadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["answerSearch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/senders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["senders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["openapi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Document: {
            /** Format: uint64 */
            document_id: number;
            content_hash: number[];
            /** @enum {string} */
            media_type: "pdf" | "image";
            filename: string;
            title?: string | null;
            sender?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            added_at: string;
            /** Format: date-time */
            updated_at: string;
            /** @enum {string|null} */
            title_source?: "ai" | "manual" | null;
            /** @enum {string|null} */
            sender_source?: "ai" | "manual" | null;
            /** @enum {string|null} */
            created_at_source?: "ai" | "manual" | null;
            page_count: number;
            /** Format: uint64 */
            file_size: number;
            /** @enum {string} */
            status: "STORED" | "PREVIEWING" | "OCR" | "TEXT_READY" | "EMBEDDING" | "INDEXING" | "READY" | "FAILED";
            last_error?: string | null;
            retry_count: number;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        DocumentPatch: {
            title?: string | null;
            sender?: string | null;
            /** Format: date-time */
            created_at?: string | null;
        };
        /**
         * @default document_date_desc
         * @enum {string}
         */
        DocumentSort: "document_date_desc" | "document_date_asc" | "added_date_desc" | "added_date_asc" | "title_asc" | "title_desc" | "sender_asc" | "sender_desc" | "file_size_asc" | "file_size_desc";
        DocumentPageResult: {
            items: components["schemas"]["Document"][];
            page: number;
            page_size: number;
            total: number;
        };
        OcrBlock: {
            label: string;
            bbox: number[];
            text: string;
        };
        PageInfo: {
            page: number;
            thumbnail_ready: boolean;
            text?: string | null;
            blocks: components["schemas"]["OcrBlock"][];
            html?: string | null;
        };
        SearchRequest: {
            query: string;
            page: number;
            page_size: number;
            sender?: string | null;
            /** Format: date-time */
            created_from?: string | null;
            /** Format: date-time */
            created_to?: string | null;
            /** @default false */
            skip_inferred_sender: boolean;
            /** @default false */
            skip_inferred_dates: boolean;
        };
        SearchPassage: {
            /** Format: uint64 */
            chunk_id: number;
            page: number;
            char_start: number;
            char_end: number;
            snippet: string;
            score: number;
        };
        SearchHit: {
            document: components["schemas"]["Document"];
            /** Format: uint64 */
            best_chunk_id: number;
            page: number;
            snippet: string;
            score: number;
            passages: components["schemas"]["SearchPassage"][];
        };
        SearchInterpretation: {
            sender: string | null;
            /** Format: date-time */
            created_from: string | null;
            /** Format: date-time */
            created_to: string | null;
        };
        SearchResponse: {
            items: components["schemas"]["SearchHit"][];
            page: number;
            page_size: number;
            total: number;
            interpretation: components["schemas"]["SearchInterpretation"];
        };
        SearchAnswerRequest: {
            query: string;
            chunk_ids: number[];
        };
        SearchAnswerResponse: {
            answer: string | null;
            citations: number[];
        };
        HealthResponse: {
            status: string;
            ocr_configured: boolean;
            ocr_base_url: string;
            ocr_model: string;
            metadata_model: string;
            embedding_configured: boolean;
            embedding_model: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                query?: string | null;
                sender?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                sort?: components["schemas"]["DocumentSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Documents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPageResult"];
                };
            };
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                    /** Format: date-time */
                    created_at?: string;
                };
            };
        };
        responses: {
            /** @description Existing document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patchDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    getDocumentFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Original file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDocumentPages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageInfo"][];
                };
            };
        };
    };
    getThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebP thumbnail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPageImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WebP page render at OCR resolution */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    retryDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retried */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    inferDocumentMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata inferred */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    answerSearch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAnswerRequest"];
            };
        };
        responses: {
            /** @description Citation-backed search answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchAnswerResponse"];
                };
            };
        };
    };
    senders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Known senders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    openapi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
